### ISSUE TITLE
Test crowdloan strategy

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/Basilisk-node#38]
test onboarding parachain via auction/crowdloan, inclusion, block production and runtime update
- [x] with rococo-local
- [ ] (optional) with kusama forkoff

**Comment by green-jay** [comment]
tested with Rococo local successfully:
- register parathread
- start crowdloan
- start auction
- include winner parachain
- runtime upgrade of parachain

I observed that when connected to relay (rococo), sending extrinsics from PolkadotJS apps, the types required were:
```
{
  "Address": "MultiAddress",
  "LookupSource": "MultiAddress"
}
```

whereas when sending an extrinsic when connected to parachain and doing runtime upgrade, it required:
```
{
  "Address": "AccountId",
  "LookupSource": "AccountId"
}

```
otherwise errors (cannot decode type XX) were thrown
