### ISSUE TITLE
Generate rustdocs workflow

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/Basilisk-node#380]
- [ ] generate runtime / rustdocs
- [ ] deploy docs to gh pages
- [ ] set custom domain
- [ ] link to https://docs.bsx.fi/
- [ ] add to ci workflow

**Comment by Roznovjak** [comment]
update on the workflow I am testing:

- [ ] create `gh-pages` branch where the docs will be stored
- [ ] set the `gh-pages` branch for github pages in the Settings -> Pages -> Source
- [ ] the docs are built conditionally when a PR is merged into the master branch to avoid regenerating and deploying of the docs on every commit to a PR
- [ ] build the docs in the existing workflow along the build process to avoid rebuilding the sources
- [ ] force push the docs to the `gh-pages` branch

- [ ] create dummy `index.html` file in the root dir of the `gh-pages` branch redirecting to the main `index.html` file nested in a subfolder. Otherwise the gh page results in the 404 error.
- [ ] add link to the docs from `docs.bsx.fi`

**Comment by Roznovjak** [comment]
Had to create a separate workflow. It looks like it is not possible to conditionally run a job from our existing workflow only when a PR is merged.

**Comment by lumir-mrkva** [comment]
> Had to create a separate workflow. It looks like it is not possible to conditionally run a job from our existing workflow only when a PR is merged.

separate workflow can be ok in this case, but regardless, this should be possible, we are already doing something similar for testnet deployment https://github.com/galacticcouncil/Basilisk-node/blob/master/.github/workflows/workflow.yml#L193
(check that this is not running in PR and only in correct branch)

**Comment by Roznovjak** [comment]
> > Had to create a separate workflow. It looks like it is not possible to conditionally run a job from our existing workflow only when a PR is merged.
> 
> separate workflow can be ok in this case, but regardless, this should be possible, we are already doing something similar for testnet deployment https://github.com/galacticcouncil/Basilisk-node/blob/master/.github/workflows/workflow.yml#L193 (check that this is not running in PR and only in correct branch)

I tried to use this condition `if: github.event.pull_request.merged == true`, but it was not set in our workflow.
